### ISSUE TITLE
Unable to run the jar

### ISSUE THREAD

**Issue by thomaspeeters** [NielsBillen/pocoloco#1]
Hi,

I downloaded the jar file (which looks great based on the screenshot), but I am unable to run it. I have installed Java on Windows 10, but get "A JNI error has occurred ... "., followed by "A Java exception has occurred". Are there any system requirements for running this jar?
Decompiling it with Eclipse also gives me a whole bunch of type mismatch exceptions.

**Comment by NielsBillen** [comment]
Hi Thomas,

There are no specific system requirements. I'm able to run the JAR on using the OpenJDK 16 (https://adoptopenjdk.net/) on my Windows 11 laptop. What version of JDK are you using?

Kind regards,
Niels

**Comment by thomaspeeters** [comment]
I was just using the latest Java Runtime Environment. I had no Java or Java IDE installed on my system before today, I installed those to try and get this jar working.
I installed OpenJDK 16 and it works now. Thank you!

**Comment by mvanduijker** [comment]
I tried to run it on MacOS but I get the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	no swt-win32-4936r26 in java.library.path: /Users/John/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-win32 in java.library.path: /Users/John/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/John/.swt/lib/macosx/aarch64/libswt-win32-4936r26.jnilib
	Can't load library: /Users/John/.swt/lib/macosx/aarch64/libswt-win32.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:338)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:145)
	at ui.PocoLocoUserInterface.open(PocoLocoUserInterface.java:85)
	at ui.PocoLocoUserInterface.main(PocoLocoUserInterface.java:319)
```

Looks like it's linking hard to win32 version of SWT? SWT should be multi platform.
